#ifndef CPU_OFFSETS_H
#define CPU_OFFSETS_H

#define CPU_OFFSET_STACK 0
#define CPU_OFFSET_STACK_TOP 8
#define CPU_OFFSET_JIT_CONTEXT 16
#define CPU_OFFSET_CURRENT_MODULE 24
#define CPU_OFFSET_GLOBAL_VALS 32
#define CPU_OFFSET_GLOBAL_SIZE 40
#define CPU_OFFSET_INTERRUPTED 64

#endif
